# Generated by Django 2.2.19 on 2021-03-12 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adpet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='phone',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
