# Generated by Django 2.2.19 on 2021-03-18 00:36

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Big', 'Big')], max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Specie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specie', models.CharField(choices=[('Cat', 'Cat'), ('Dog', 'Dog')], max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sterilized',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sterilized', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vaccinated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccinated', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2, 'Title must be greater than 2 characters')])),
                ('breed', models.CharField(max_length=30, null=True)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('age', models.IntegerField(null=True)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('picture', models.BinaryField(editable=True, null=True)),
                ('content_type', models.CharField(help_text='The MIMEType of the file', max_length=256, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=100, null=True)),
                ('gender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Gender')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adhome_petowned', to=settings.AUTH_USER_MODEL)),
                ('size', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Size')),
                ('specie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Specie')),
                ('sterilized', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Sterilized')),
                ('vaccinated', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Vaccinated')),
            ],
        ),
    ]
